import cv2 as cv
import numpy as np
img = cv.imread('Resources\Photos\cat.jpg')
cv.imshow("Cat",img)
blank = np.zeros(img.shape,dtype='uint8')
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow("Gray",gray)
canny = cv.Canny(img,125,175)
cv.imshow("Canny",canny)
ret, thresh = cv.threshold(gray,125,255,cv.THRESH_BINARY)
cv.imshow("Thresh",thresh)
countours,hierarchies = cv.findContours(thresh,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE)
print(f'{len(countours)}')
cv.drawContours(blank,countours,-1,(0,0,255),10)
cv.imshow("Countours",blank)
cv.waitKey(0)